/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ytech_ndksample_NDKTools */

#ifndef _Included_com_ytech_ndksample_NDKTools
#define _Included_com_ytech_ndksample_NDKTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ytech_ndksample_NDKTools
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ytech_ndksample_NDKTools_getStringFromNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
